
package endpoint;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILibrarianService", targetNamespace = "http://endpoint/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILibrarianService {


    /**
     * 
     * @return
     *     returns java.util.List<endpoint.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsersList", targetNamespace = "http://endpoint/", className = "endpoint.GetUsersList")
    @ResponseWrapper(localName = "getUsersListResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetUsersListResponse")
    @Action(input = "http://endpoint/ILibrarianService/getUsersListRequest", output = "http://endpoint/ILibrarianService/getUsersListResponse")
    public List<User> getUsersList();

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.Operation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDebtors", targetNamespace = "http://endpoint/", className = "endpoint.FindDebtors")
    @ResponseWrapper(localName = "findDebtorsResponse", targetNamespace = "http://endpoint/", className = "endpoint.FindDebtorsResponse")
    @Action(input = "http://endpoint/ILibrarianService/findDebtorsRequest", output = "http://endpoint/ILibrarianService/findDebtorsResponse")
    public List<Operation> findDebtors();

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://endpoint/", className = "endpoint.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetAllBooksResponse")
    @Action(input = "http://endpoint/ILibrarianService/getAllBooksRequest", output = "http://endpoint/ILibrarianService/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.UserOrder>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserOrders", targetNamespace = "http://endpoint/", className = "endpoint.GetUserOrders")
    @ResponseWrapper(localName = "getUserOrdersResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetUserOrdersResponse")
    @Action(input = "http://endpoint/ILibrarianService/getUserOrdersRequest", output = "http://endpoint/ILibrarianService/getUserOrdersResponse")
    public List<UserOrder> getUserOrders();

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.Store>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStores", targetNamespace = "http://endpoint/", className = "endpoint.GetStores")
    @ResponseWrapper(localName = "getStoresResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetStoresResponse")
    @Action(input = "http://endpoint/ILibrarianService/getStoresRequest", output = "http://endpoint/ILibrarianService/getStoresResponse")
    public List<Store> getStores();

    /**
     * 
     * @param userID
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unlockDebtor", targetNamespace = "http://endpoint/", className = "endpoint.UnlockDebtor")
    @ResponseWrapper(localName = "unlockDebtorResponse", targetNamespace = "http://endpoint/", className = "endpoint.UnlockDebtorResponse")
    @Action(input = "http://endpoint/ILibrarianService/unlockDebtorRequest", output = "http://endpoint/ILibrarianService/unlockDebtorResponse")
    public Integer unlockDebtor(
        @WebParam(name = "userID", targetNamespace = "")
        int userID);

    /**
     * 
     * @param pubHouse
     * @param stitle
     * @param pubYear
     * @param author
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewBook", targetNamespace = "http://endpoint/", className = "endpoint.AddNewBook")
    @ResponseWrapper(localName = "addNewBookResponse", targetNamespace = "http://endpoint/", className = "endpoint.AddNewBookResponse")
    @Action(input = "http://endpoint/ILibrarianService/addNewBookRequest", output = "http://endpoint/ILibrarianService/addNewBookResponse")
    public Integer addNewBook(
        @WebParam(name = "Stitle", targetNamespace = "")
        String stitle,
        @WebParam(name = "author", targetNamespace = "")
        String author,
        @WebParam(name = "pubHouse", targetNamespace = "")
        String pubHouse,
        @WebParam(name = "pubYear", targetNamespace = "")
        int pubYear);

    /**
     * 
     * @param purchaseDate
     * @param count
     * @param shopID
     * @param bookID
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "purchaseBook", targetNamespace = "http://endpoint/", className = "endpoint.PurchaseBook")
    @ResponseWrapper(localName = "purchaseBookResponse", targetNamespace = "http://endpoint/", className = "endpoint.PurchaseBookResponse")
    @Action(input = "http://endpoint/ILibrarianService/purchaseBookRequest", output = "http://endpoint/ILibrarianService/purchaseBookResponse")
    public Integer purchaseBook(
        @WebParam(name = "bookID", targetNamespace = "")
        int bookID,
        @WebParam(name = "shopID", targetNamespace = "")
        int shopID,
        @WebParam(name = "count", targetNamespace = "")
        int count,
        @WebParam(name = "purchaseDate", targetNamespace = "")
        XMLGregorianCalendar purchaseDate);

    /**
     * 
     * @param userID
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lockDebtor", targetNamespace = "http://endpoint/", className = "endpoint.LockDebtor")
    @ResponseWrapper(localName = "lockDebtorResponse", targetNamespace = "http://endpoint/", className = "endpoint.LockDebtorResponse")
    @Action(input = "http://endpoint/ILibrarianService/lockDebtorRequest", output = "http://endpoint/ILibrarianService/lockDebtorResponse")
    public Integer lockDebtor(
        @WebParam(name = "userID", targetNamespace = "")
        int userID);

    /**
     * 
     * @param password
     * @param name
     * @param login
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registration", targetNamespace = "http://endpoint/", className = "endpoint.Registration")
    @ResponseWrapper(localName = "registrationResponse", targetNamespace = "http://endpoint/", className = "endpoint.RegistrationResponse")
    @Action(input = "http://endpoint/ILibrarianService/registrationRequest", output = "http://endpoint/ILibrarianService/registrationResponse")
    public int registration(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param address
     * @param phone
     * @param name
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewStore", targetNamespace = "http://endpoint/", className = "endpoint.AddNewStore")
    @ResponseWrapper(localName = "addNewStoreResponse", targetNamespace = "http://endpoint/", className = "endpoint.AddNewStoreResponse")
    @Action(input = "http://endpoint/ILibrarianService/addNewStoreRequest", output = "http://endpoint/ILibrarianService/addNewStoreResponse")
    public int addNewStore(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "address", targetNamespace = "")
        String address);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns endpoint.AuthWrap
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorization", targetNamespace = "http://endpoint/", className = "endpoint.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://endpoint/", className = "endpoint.AuthorizationResponse")
    @Action(input = "http://endpoint/ILibrarianService/authorizationRequest", output = "http://endpoint/ILibrarianService/authorizationResponse")
    public AuthWrap authorization(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.Operation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookOperations", targetNamespace = "http://endpoint/", className = "endpoint.GetBookOperations")
    @ResponseWrapper(localName = "getBookOperationsResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetBookOperationsResponse")
    @Action(input = "http://endpoint/ILibrarianService/getBookOperationsRequest", output = "http://endpoint/ILibrarianService/getBookOperationsResponse")
    public List<Operation> getBookOperations();

    /**
     * 
     * @return
     *     returns endpoint.HashMapWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksInLibrary", targetNamespace = "http://endpoint/", className = "endpoint.GetBooksInLibrary")
    @ResponseWrapper(localName = "getBooksInLibraryResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetBooksInLibraryResponse")
    @Action(input = "http://endpoint/ILibrarianService/getBooksInLibraryRequest", output = "http://endpoint/ILibrarianService/getBooksInLibraryResponse")
    public HashMapWrapper getBooksInLibrary();

    /**
     * 
     * @return
     *     returns java.util.List<endpoint.PurchaseOrder>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPurchaseOrders", targetNamespace = "http://endpoint/", className = "endpoint.GetPurchaseOrders")
    @ResponseWrapper(localName = "getPurchaseOrdersResponse", targetNamespace = "http://endpoint/", className = "endpoint.GetPurchaseOrdersResponse")
    @Action(input = "http://endpoint/ILibrarianService/getPurchaseOrdersRequest", output = "http://endpoint/ILibrarianService/getPurchaseOrdersResponse")
    public List<PurchaseOrder> getPurchaseOrders();

}
